name: TFLint

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: terraform-linters/setup-tflint@v4

      - run: tflint --init

      - run: tflint --recursive