name: Trivy Scan

on:
  push:
    branches:
      - develop
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs